# Use an existing docker image as base
FROM node:alpine

WORKDIR /usr/app

# Download and install dependencies
COPY ./package.json ./
RUN npm install

COPY ./ ./

# Starting image container instructions
CMD ["npm", "run", "start"]


