version: "3"
# services define types of containers
# docker-compose automatically networks defined containers
services:
  # redis-server:
  #   image: redis
  #   # optional: specifiy 6379 default port
  #   ports:
  #     - "6379"
  web:
    # restart: always
    stdin_open: true
    # specifies Dockerfile for build
    # build: ./
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
  tests:
    # restart: always
    # stdin_open: true
    # specifies Dockerfile for build
    # build: ./
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]
